# Generated by Django 4.2.18 on 2026-03-24 15:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("seats_pattern", models.CharField(max_length=500)),
                ("changed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("event_time", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("published", "Published")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("number_of_visitors", models.PositiveIntegerField(default=0)),
                ("changed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("status_changed_at", models.DateTimeField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.place",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "ticket_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seat", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["registered_at"],
                "unique_together": {("event", "seat")},
            },
        ),
    ]
